# Generated by Django 5.2 on 2025-05-22 18:23

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('appointment_date', models.DateField(blank=True, null=True, verbose_name='Data de Nomeação')),
                ('appointment_validity', models.DateField(blank=True, null=True, verbose_name='Validade da Nomeação')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('dpo', 'DPO'), ('manager', 'Gerente')], default='manager', max_length=20, verbose_name='Função do Usuário')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ExigenciaLGPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Exigência')),
                ('descricao', models.TextField(verbose_name='Descrição Detalhada')),
                ('artigos_referencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Artigos de Referência (LGPD)')),
                ('arquivo_comprovacao', models.FileField(blank=True, null=True, upload_to='comprovantes_lgpd/', verbose_name='Arquivo de Comprovação')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('upload_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Upload feito por')),
            ],
            options={
                'verbose_name': 'Exigência da LGPD',
                'verbose_name_plural': 'Exigências da LGPD',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='InventarioDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_processo', models.CharField(max_length=255, verbose_name='Nome do Processo')),
                ('tipo_dado', models.CharField(choices=[('comuns', 'Dados Pessoais Comuns'), ('sensíveis', 'Dados Pessoais Sensíveis'), ('anonimizados', 'Dados Anonimizados'), ('pseudonimizados', 'Dados Pseudonimizados')], max_length=100, verbose_name='Tipo de Dado Pessoal')),
                ('finalidade_coleta', models.TextField(verbose_name='Finalidade da Coleta')),
                ('base_legal', models.CharField(max_length=255, verbose_name='Base Legal da LGPD')),
                ('forma_coleta', models.CharField(max_length=255, verbose_name='Forma de Coleta')),
                ('periodo_retencao', models.CharField(max_length=100, verbose_name='Período de Retenção')),
                ('compartilhamento_terceiros', models.BooleanField(default=False, verbose_name='Compartilhamento com Terceiros?')),
                ('nome_terceiro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Terceiro (se houver)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações Adicionais')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Inventário de Dados',
                'verbose_name_plural': 'Inventários de Dados',
                'ordering': ['nome_processo'],
            },
        ),
        migrations.CreateModel(
            name='MatrizRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_risco', models.TextField(verbose_name='Descrição do Risco')),
                ('probabilidade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=50, verbose_name='Probabilidade')),
                ('impacto', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], max_length=50, verbose_name='Impacto')),
                ('nivel_risco', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nível de Risco Calculado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riscos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('processo_afetado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riscos', to='api.inventariodados', verbose_name='Processo Afetado')),
            ],
            options={
                'verbose_name': 'Matriz de Risco',
                'verbose_name_plural': 'Matrizes de Risco',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PlanoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao_mitigacao', models.TextField(verbose_name='Ação de Mitigação')),
                ('data_limite', models.DateField(verbose_name='Data Limite para Conclusão')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='Pendente', max_length=50, verbose_name='Status da Ação')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações do Plano de Ação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Ação')),
                ('risco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_acao', to='api.matrizrisco', verbose_name='Risco Associado')),
            ],
            options={
                'verbose_name': 'Plano de Ação',
                'verbose_name_plural': 'Planos de Ação',
                'ordering': ['data_limite'],
            },
        ),
    ]
