# Generated by Django 5.2.4 on 2025-08-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(max_length=255, verbose_name='Atividade')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Concluído')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Checklist LGPD',
                'verbose_name_plural': 'Checklist LGPD',
                'ordering': ['created_at'],
            },
        ),
    ]
