# Generated by Django 5.2 on 2025-06-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventariodados',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Inventário de Dados', 'verbose_name_plural': 'Inventários de Dados'},
        ),
        migrations.RemoveField(
            model_name='inventariodados',
            name='compartilhamento_terceiros',
        ),
        migrations.RemoveField(
            model_name='inventariodados',
            name='finalidade_coleta',
        ),
        migrations.RemoveField(
            model_name='inventariodados',
            name='forma_coleta',
        ),
        migrations.RemoveField(
            model_name='inventariodados',
            name='nome_processo',
        ),
        migrations.RemoveField(
            model_name='inventariodados',
            name='nome_terceiro',
        ),
        migrations.RemoveField(
            model_name='inventariodados',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='adequado_contrato',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('nao_aplica', 'Não se Aplica')], default='', max_length=20, verbose_name='Adequado contratualmente?'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='ativos_associados',
            field=models.CharField(default='', max_length=255, verbose_name='Ativos associados'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='atualizacoes',
            field=models.CharField(default='', max_length=255, verbose_name='Atualizações'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='consentimentos',
            field=models.CharField(default='', max_length=255, verbose_name='Consentimentos'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='controlador_operador',
            field=models.CharField(choices=[('controlador', 'Controlador'), ('operador', 'Operador'), ('ambos', 'Controlador / Operador'), ('nao_aplica', 'Não se Aplica')], default='', max_length=30, verbose_name='Controlador / Operador'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='dados_menores',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('nao_aplica', 'Não se Aplica')], default='', max_length=20, verbose_name='Dados de criança / adolescente ou vulnerável'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='dados_pessoais_tratados',
            field=models.TextField(default='', verbose_name='Dados pessoais tratados'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='dados_transferidos',
            field=models.CharField(default='', max_length=255, verbose_name='Dados são transferidos'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='empresa_terceira',
            field=models.CharField(default='', max_length=255, verbose_name='Empresa terceira'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='exclusao',
            field=models.CharField(default='', max_length=100, verbose_name='Exclusão'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='finalidade',
            field=models.TextField(default='', verbose_name='Finalidade'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='forma_exclusao',
            field=models.CharField(default='', max_length=255, verbose_name='Forma de exclusão'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='formato',
            field=models.CharField(choices=[('fisico', 'Físico'), ('digital', 'Digital'), ('ambos', 'Físico / Digital')], default='', max_length=30, verbose_name='Formato'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='impresso',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='', max_length=10, verbose_name='É impresso?'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='locais_armazenamento',
            field=models.CharField(default='', max_length=255, verbose_name='Locais de armazenamento (Digital e físico)'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='medidas_seguranca',
            field=models.CharField(default='', max_length=255, verbose_name='Medidas de segurança envolvidas'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='motivo_retencao',
            field=models.CharField(default='', max_length=255, verbose_name='Motivo da retenção'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='observacao_extra',
            field=models.TextField(default='', verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='origem',
            field=models.TextField(default='', verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='paises_env_tratamento',
            field=models.CharField(default='', max_length=255, verbose_name='Países envolvidos no tratamento'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='pessoas_acesso',
            field=models.CharField(default='', max_length=255, verbose_name='Pessoas com acesso'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='processo',
            field=models.CharField(default='', max_length=255, verbose_name='Processo de negócio'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='responsavel',
            field=models.CharField(default='', max_length=255, verbose_name='Responsável (Email)'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='setor',
            field=models.CharField(default='', max_length=255, verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='titular_dados',
            field=models.CharField(default='', max_length=255, verbose_name='Titular dos dados'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='transf_internacional',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não'), ('nao_aplica', 'Não se Aplica')], default='', max_length=20, verbose_name='Ocorre transferência internacional?'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='transf_terceiros',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='', max_length=10, verbose_name='Transferência para terceiros?'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='transmissao_externa',
            field=models.CharField(default='', max_length=255, verbose_name='Transmissão externa'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='transmissao_interna',
            field=models.CharField(default='', max_length=255, verbose_name='Transmissão interna'),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='unidade',
            field=models.CharField(choices=[('matriz', 'Matriz'), ('filial', 'Filial'), ('ambos', 'Matriz / Filial')], default='', max_length=20, verbose_name='Matriz / Filial'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='base_legal',
            field=models.TextField(default='', verbose_name='Base legal'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='periodo_retencao',
            field=models.CharField(default='', max_length=100, verbose_name='Período de Retenção'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='tipo_dado',
            field=models.CharField(choices=[('sensivel', 'Sensível'), ('nao_sensivel', 'Não Sensível'), ('ambos', 'Sensível e Não Sensível'), ('nao_aplica', 'Não se Aplica')], default='', max_length=100, verbose_name='Tipo de Dado'),
        ),
    ]
