# Generated by Django 5.2 on 2025-06-09 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_inventariodados_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrizrisco',
            name='nivel_risco',
        ),
        migrations.RemoveField(
            model_name='matrizrisco',
            name='processo_afetado',
        ),
        migrations.AddField(
            model_name='matrizrisco',
            name='controle_existente',
            field=models.CharField(default='', max_length=255, verbose_name='Controle existente'),
        ),
        migrations.AddField(
            model_name='matrizrisco',
            name='eficacia_controle',
            field=models.CharField(default='', max_length=2, verbose_name='Avaliação da Eficácia do Controle [1-5]'),
        ),
        migrations.AddField(
            model_name='matrizrisco',
            name='pontuacao_risco',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Pontuação do Risco (P x I)'),
        ),
        migrations.AddField(
            model_name='matrizrisco',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='riscos', to='api.inventariodados', verbose_name='Processo de negócio'),
        ),
        migrations.AddField(
            model_name='matrizrisco',
            name='resposta_ao_risco',
            field=models.TextField(default='', verbose_name='Resposta ao Risco'),
        ),
        migrations.AddField(
            model_name='matrizrisco',
            name='risco_residual',
            field=models.CharField(choices=[('alto', 'Alto'), ('medio', 'Médio'), ('baixo', 'Baixo'), ('nao_se_aplica', 'Não se aplica')], default='', max_length=20, verbose_name='Risco Residual'),
        ),
        migrations.AddField(
            model_name='matrizrisco',
            name='tipo_controle',
            field=models.CharField(choices=[('preventivo', 'Preventivo'), ('detectivo', 'Detectivo'), ('nao_se_aplica', 'Não se aplica')], default='', max_length=20, verbose_name='Tipo de Controle'),
        ),
        migrations.AlterField(
            model_name='matrizrisco',
            name='descricao_risco',
            field=models.TextField(default='', verbose_name='Descrição do Risco'),
        ),
        migrations.AlterField(
            model_name='matrizrisco',
            name='impacto',
            field=models.CharField(default='', max_length=2, verbose_name='Impacto [1-5]'),
        ),
        migrations.AlterField(
            model_name='matrizrisco',
            name='probabilidade',
            field=models.CharField(default='', max_length=2, verbose_name='Probabilidade [1-5]'),
        ),
    ]
