# Generated by Django 5.2.4 on 2025-08-12 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_checklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
