# Generated by Django 5.2 on 2025-06-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_matrizrisco_nivel_risco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariodados',
            name='adequado_contrato',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não'), ('nao_aplica', 'Não se Aplica')], default='', max_length=20, verbose_name='Adequado contratualmente?'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='ativos_associados',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Ativos associados'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='atualizacoes',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Atualizações'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='base_legal',
            field=models.TextField(blank=True, default='', verbose_name='Base legal'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='consentimentos',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Consentimentos'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='controlador_operador',
            field=models.CharField(blank=True, choices=[('controlador', 'Controlador'), ('operador', 'Operador'), ('ambos', 'Controlador / Operador'), ('nao_aplica', 'Não se Aplica')], default='', max_length=30, verbose_name='Controlador / Operador'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='dados_menores',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não'), ('nao_aplica', 'Não se Aplica')], default='', max_length=20, verbose_name='Dados de criança / adolescente ou vulnerável'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='dados_pessoais_tratados',
            field=models.TextField(blank=True, default='', verbose_name='Dados pessoais tratados'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='dados_transferidos',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Dados são transferidos'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='empresa_terceira',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Empresa terceira'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='exclusao',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Exclusão'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='finalidade',
            field=models.TextField(blank=True, default='', verbose_name='Finalidade'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='forma_exclusao',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Forma de exclusão'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='formato',
            field=models.CharField(blank=True, choices=[('fisico', 'Físico'), ('digital', 'Digital'), ('ambos', 'Físico / Digital')], default='', max_length=30, verbose_name='Formato'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='impresso',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='', max_length=10, verbose_name='É impresso?'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='locais_armazenamento',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Locais de armazenamento (Digital e físico)'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='medidas_seguranca',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Medidas de segurança envolvidas'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='motivo_retencao',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Motivo da retenção'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='observacao_extra',
            field=models.TextField(blank=True, default='', verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='paises_env_tratamento',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Países envolvidos no tratamento'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='periodo_retencao',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Período de Retenção'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='pessoas_acesso',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Pessoas com acesso'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='processo',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Processo de negócio'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='responsavel',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Responsável (Email)'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='setor',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='tipo_dado',
            field=models.CharField(blank=True, choices=[('sensivel', 'Sensível'), ('nao_sensivel', 'Não Sensível'), ('ambos', 'Sensível e Não Sensível'), ('nao_aplica', 'Não se Aplica')], default='', max_length=100, verbose_name='Tipo de Dado'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='titular_dados',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Titular dos dados'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='transf_internacional',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não'), ('nao_aplica', 'Não se Aplica')], default='', max_length=20, verbose_name='Ocorre transferência internacional?'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='transf_terceiros',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], default='', max_length=10, verbose_name='Transferência para terceiros?'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='transmissao_externa',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Transmissão externa'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='transmissao_interna',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Transmissão interna'),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='unidade',
            field=models.CharField(blank=True, choices=[('matriz', 'Matriz'), ('filial', 'Filial'), ('ambos', 'Matriz / Filial')], default='', max_length=20, verbose_name='Matriz / Filial'),
        ),
        migrations.AlterField(
            model_name='matrizrisco',
            name='controle_existente',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Controle existente'),
        ),
        migrations.AlterField(
            model_name='matrizrisco',
            name='eficacia_controle',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('na', 'Não se aplica'), ('', '---------')], default='', max_length=20, verbose_name='Avaliação da Eficácia do Controle [1-5]'),
        ),
        migrations.AlterField(
            model_name='matrizrisco',
            name='impacto',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=1, verbose_name='Impacto [1-5]'),
        ),
        migrations.AlterField(
            model_name='matrizrisco',
            name='pontuacao_risco',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Pontuação do Risco'),
        ),
        migrations.AlterField(
            model_name='matrizrisco',
            name='probabilidade',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=1, verbose_name='Probabilidade [1-5]'),
        ),
        migrations.AlterField(
            model_name='matrizrisco',
            name='resposta_ao_risco',
            field=models.TextField(blank=True, default='', verbose_name='Resposta ao Risco'),
        ),
        migrations.AlterField(
            model_name='matrizrisco',
            name='risco_residual',
            field=models.CharField(blank=True, choices=[('alto', 'Alto'), ('medio', 'Médio'), ('baixo', 'Baixo'), ('nao_se_aplica', 'Não se aplica')], default='', max_length=20, verbose_name='Risco Residual'),
        ),
        migrations.AlterField(
            model_name='matrizrisco',
            name='tipo_controle',
            field=models.CharField(blank=True, choices=[('preventivo', 'Preventivo'), ('detectivo', 'Detectivo'), ('nao_se_aplica', 'Não se aplica')], default='', max_length=20, verbose_name='Tipo de Controle'),
        ),
    ]
