# Generated by Django 5.2.4 on 2025-08-13 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('dpo', 'DPO'), ('gerente', 'Gerente')], default='gerente', max_length=20, verbose_name='Função do Usuário'),
        ),
    ]
