# Generated by Django 5.2 on 2025-06-10 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_inventariodados_adequado_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoacao',
            name='status',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='', max_length=50, verbose_name='Status da Ação'),
        ),
        migrations.CreateModel(
            name='ExigenciasLGPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimensao', models.CharField(choices=[('gestao_privacidade', 'Gestão de Privacidade'), ('gestao_si', 'Gestão de Segurança da Informação'), ('processos', 'Processos')], max_length=100, verbose_name='Dimensão')),
                ('atividade', models.TextField(verbose_name='Atividade')),
                ('base_legal', models.CharField(blank=True, max_length=255, null=True, verbose_name='Base Legal')),
                ('evidencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Evidência')),
                ('proxima_revisao', models.DateField(blank=True, null=True, verbose_name='Próxima Revisão')),
                ('classificacao', models.CharField(blank=True, choices=[('boas_praticas', 'Boas práticas'), ('baixa', 'Baixa criticidade'), ('media', 'Média criticidade'), ('alta', 'Alta criticidade'), ('nao_aplicavel', 'Não aplicável')], default='', max_length=20, verbose_name='Classificação')),
                ('status', models.CharField(blank=True, choices=[('nao_iniciado', 'Não iniciado'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('nao_aplicavel', 'Não aplicável')], default='', max_length=20, verbose_name='Status')),
                ('acoes', models.CharField(blank=True, choices=[('visualizar', 'Visualizar'), ('editar', 'Editar'), ('excluir', 'Excluir'), ('upload', 'Upload'), ('download', 'Download')], default='', max_length=20, verbose_name='Ações Disponíveis')),
                ('arquivo_comprovacao', models.FileField(blank=True, null=True, upload_to='comprovantes_lgpd/', verbose_name='Arquivo de Comprovação')),
                ('data_upload', models.DateTimeField(auto_now_add=True, verbose_name='Data de Upload')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('upload_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Upload feito por')),
            ],
            options={
                'verbose_name': 'Exigência da LGPD',
                'verbose_name_plural': 'Exigências da LGPD',
                'ordering': ['data_upload'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('documento_vencendo', 'Documento com vencimento próximo'), ('documento_vencido', 'Documento vencido'), ('acao_suspeita', 'Ação suspeita detectada'), ('acao_realizada', 'Ação realizada no sistema'), ('auditoria_proxima', 'Auditoria próxima'), ('auditoria_hoje', 'Auditoria hoje')], max_length=30, verbose_name='Tipo de Notificação')),
                ('mensagem', models.TextField(verbose_name='Mensagem da Notificação')),
                ('origem_externa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Origem Externa (IP, Sistema Externo, etc.)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data do Alerta')),
                ('objeto_referencia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Objeto/Documento relacionado')),
                ('data_evento', models.DateField(blank=True, null=True, verbose_name='Data do Evento relacionado')),
                ('gerado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_geradas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário que causou a ação')),
                ('lida_por', models.ManyToManyField(blank=True, related_name='notificacoes_lidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuários que leram a notificação')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.DeleteModel(
            name='ExigenciaLGPD',
        ),
    ]
