# Generated by Django 5.2.4 on 2025-09-01 15:43

import api.models
from django.db import migrations
from django.contrib.auth.models import UserManager


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_user_avatar"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", UserManager()),
            ],
        ),
    ]
