# Generated by Django 5.2 on 2025-06-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_planoacao_status_exigenciaslgpd_notificacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrizrisco',
            name='impacto',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, null=True, verbose_name='Impacto [1-5]'),
        ),
        migrations.AlterField(
            model_name='matrizrisco',
            name='probabilidade',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None, null=True, verbose_name='Probabilidade [1-5]'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('documento_vencendo', 'Documento com vencimento próximo'), ('documento_vencido', 'Documento vencido'), ('acao_suspeita', 'Ação suspeita detectada'), ('acao_realizada', 'Ação realizada no sistema'), ('auditoria_proxima', 'Auditoria próxima'), ('auditoria_hoje', 'Auditoria hoje'), ('solicitacao_exclusao', 'Solicitação de Exclusão')], max_length=30, verbose_name='Tipo de Notificação'),
        ),
    ]
