# Generated by Django 5.2.4 on 2025-09-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_user_job_title_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventariodados',
            options={'ordering': ('-data_criacao',), 'verbose_name': 'Inventário de Dados', 'verbose_name_plural': 'Inventários de Dados'},
        ),
        migrations.RemoveField(
            model_name='inventariodados',
            name='compartilhamento_terceiros',
        ),
        migrations.RemoveField(
            model_name='inventariodados',
            name='finalidade_coleta',
        ),
        migrations.RemoveField(
            model_name='inventariodados',
            name='forma_coleta',
        ),
        migrations.RemoveField(
            model_name='inventariodados',
            name='nome_processo',
        ),
        migrations.RemoveField(
            model_name='inventariodados',
            name='nome_terceiro',
        ),
        migrations.RemoveField(
            model_name='inventariodados',
            name='observacoes',
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='adequado_contratualmente',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='atualizacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='consentimentos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='controlador_operador',
            field=models.CharField(blank=True, choices=[('controlador', 'Controlador'), ('operador', 'Operador'), ('ambos', 'Ambos')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='dados_menores',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='dados_pessoais',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='empresa_terceira',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='exclusao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='finalidade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='forma_exclusao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='formato',
            field=models.CharField(blank=True, choices=[('digital', 'Digital'), ('fisico', 'Físico'), ('hibrido', 'Híbrido')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='impresso',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='local_armazenamento_digital',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='medidas_seguranca',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='motivo_retencao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='origem',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='paises_tratamento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='pessoas_acesso',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='processo_negocio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='quais_dados_transferidos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='responsavel_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='setor',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='titulares',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='transferencia_internacional',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='transferencia_terceiros',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='transmissao_externa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='transmissao_interna',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventariodados',
            name='unidade',
            field=models.CharField(blank=True, choices=[('matriz', 'Matriz'), ('filial', 'Filial')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='base_legal',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='periodo_retencao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventariodados',
            name='tipo_dado',
            field=models.CharField(blank=True, choices=[('pessoal', 'Pessoal'), ('sensivel', 'Sensível'), ('anonimizado', 'Anonimizado')], max_length=12, null=True),
        ),
    ]
