# Generated by Django 5.2.4 on 2025-09-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_inventariodados_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariodados',
            name='formato',
            field=models.CharField(blank=True, choices=[('digital', 'Digital'), ('fisico', 'Físico'), ('físico e digital', 'Físico e Digital')], max_length=16, null=True),
        ),
    ]
