# Generated by Django 5.2.4 on 2025-09-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_inventariodados_formato'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='inventariodados',
            index=models.Index(fields=['unidade'], name='api_inventa_unidade_0aeef6_idx'),
        ),
        migrations.AddIndex(
            model_name='inventariodados',
            index=models.Index(fields=['setor'], name='api_inventa_setor_84b57c_idx'),
        ),
        migrations.AddIndex(
            model_name='inventariodados',
            index=models.Index(fields=['responsavel_email'], name='api_inventa_respons_201449_idx'),
        ),
        migrations.AddIndex(
            model_name='inventariodados',
            index=models.Index(fields=['processo_negocio'], name='api_inventa_process_161e06_idx'),
        ),
        migrations.AddIndex(
            model_name='inventariodados',
            index=models.Index(fields=['data_criacao'], name='api_inventa_data_cr_b98372_idx'),
        ),
    ]
