# Generated by Django 5.2.4 on 2025-09-04 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_inventariodados_api_inventa_unidade_0aeef6_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlEffectivenessItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(unique=True)),
                ('label_pt', models.CharField(max_length=60)),
                ('reduction_min', models.PositiveSmallIntegerField()),
                ('reduction_max', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Efetividade do Controle',
                'verbose_name_plural': 'Efetividade do Controle (itens)',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='ImpactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(unique=True)),
                ('label_pt', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Impacto',
                'verbose_name_plural': 'Impacto (itens)',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('numero_registro', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('fonte', models.CharField(max_length=120)),
                ('data_registro', models.DateField()),
                ('responsavel_analise', models.CharField(max_length=120)),
                ('data_final_analise', models.DateField(blank=True, null=True)),
                ('acao_recomendada', models.TextField(blank=True)),
                ('recomendacoes_reportadas', models.CharField(blank=True, max_length=200)),
                ('data_reporte', models.DateField(blank=True, null=True)),
                ('decisoes_resolucao', models.TextField(blank=True)),
                ('data_encerramento', models.DateField(blank=True, null=True)),
                ('fonte_informada', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body_md', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LikelihoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(unique=True)),
                ('label_pt', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Probabilidade',
                'verbose_name_plural': 'Probabilidade (itens)',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework_requisito', models.CharField(max_length=200)),
                ('escopo', models.TextField()),
                ('data_monitoramento', models.DateField()),
                ('criterio_avaliacao', models.CharField(max_length=200)),
                ('responsavel', models.CharField(max_length=120)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('deficiencias', models.TextField(blank=True)),
                ('corretivas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Ação de Monitoramento',
                'verbose_name_plural': 'Ações de Monitoramento',
            },
        ),
        migrations.CreateModel(
            name='RiskLevelBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=7)),
                ('min_score', models.PositiveSmallIntegerField()),
                ('max_score', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Nível de Risco (faixa)',
                'verbose_name_plural': 'Níveis de Risco (faixas)',
                'ordering': ['min_score'],
            },
        ),
        migrations.RemoveField(
            model_name='planoacao',
            name='risco',
        ),
        migrations.RemoveField(
            model_name='planoacao',
            name='responsavel',
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriz_filial', models.CharField(max_length=120)),
                ('setor', models.CharField(max_length=120)),
                ('processo', models.CharField(max_length=200)),
                ('risco_fator', models.TextField()),
                ('pontuacao', models.IntegerField()),
                ('existe_controle', models.BooleanField(default=False)),
                ('tipo_controle', models.CharField(blank=True, choices=[('C', 'Preventivo'), ('D', 'Detectivo')], max_length=1)),
                ('risco_residual', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], max_length=20)),
                ('resposta_risco', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('eficacia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.controleffectivenessitem')),
                ('impacto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.impactitem')),
                ('probabilidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.likelihooditem')),
            ],
            options={
                'verbose_name': 'Risco',
                'verbose_name_plural': 'Riscos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriz_filial', models.CharField(max_length=120)),
                ('setor_proprietario', models.CharField(max_length=120)),
                ('processo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('como', models.TextField(blank=True)),
                ('responsavel_execucao', models.CharField(max_length=120)),
                ('prazo', models.DateField()),
                ('status', models.CharField(choices=[('nao_iniciado', 'Não iniciado'), ('andamento', 'Em andamento'), ('concluido', 'Concluído')], max_length=20)),
                ('risco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='api.risk')),
            ],
            options={
                'verbose_name': 'Plano de Ação',
                'verbose_name_plural': 'Planos de Ação',
                'ordering': ['prazo'],
            },
        ),
        migrations.DeleteModel(
            name='MatrizRisco',
        ),
        migrations.DeleteModel(
            name='PlanoAcao',
        ),
    ]
