# Generated by Django 5.2.4 on 2025-09-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_seed_risk_conf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='pontuacao',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='risk',
            name='risco_residual',
            field=models.CharField(blank=True, choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], max_length=20),
        ),
    ]
