# Generated by Django 5.2.4 on 2025-09-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_risk_pontuacao_alter_risk_risco_residual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='existe_controle',
        ),
        migrations.AddField(
            model_name='risk',
            name='medidas_controle',
            field=models.TextField(blank=True),
        ),
    ]
