# Generated by Django 5.2.4 on 2025-09-23 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_matrizrisco_impacto_and_more"),
        ("api", "0015_remove_risk_existe_controle_risk_medidas_controle"),
    ]

    operations = []
