# Generated by Django 5.2.4 on 2025-09-16 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_remove_risk_existe_controle_risk_medidas_controle"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoLGPD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dimensao",
                    models.CharField(
                        choices=[
                            ("GPV", "Gestão de privacidade"),
                            ("GSI", "Gestão de SI"),
                            ("PRC", "Processos"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "atividade",
                    models.TextField(
                        help_text="Descrição do requisito/atividade/documento exigido"
                    ),
                ),
                ("base_legal", models.CharField(blank=True, max_length=255)),
                ("evidencia", models.CharField(blank=True, max_length=255)),
                ("proxima_revisao", models.DateField(blank=True, null=True)),
                ("comentarios", models.TextField(blank=True)),
                (
                    "criticidade",
                    models.CharField(
                        choices=[
                            ("NA", "Não aplicável"),
                            ("BP", "Boas práticas"),
                            ("BX", "Baixa"),
                            ("MD", "Média"),
                            ("AL", "Alta"),
                        ],
                        default="NA",
                        max_length=2,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NA", "Não aplicável"),
                            ("NI", "Não iniciado"),
                            ("EA", "Em andamento"),
                            ("FI", "Finalizado"),
                        ],
                        default="NI",
                        max_length=2,
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        blank=True, null=True, upload_to="documentos/%Y/%m/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ExigenciaLGPD",
        ),
    ]
