# Generated by Django 5.2.4 on 2025-09-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_documentolgpd_delete_exigencialgpd"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DocumentoLGPD",
            new_name="DocumentosLGPD",
        ),
    ]
