# Generated by Django 5.2.4 on 2025-10-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_documentolgpd_documentoslgpd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariodados',
            name='unidade',
            field=models.CharField(blank=True, choices=[('matriz', 'Matriz'), ('filial', 'Filial'), ('matriz_filial', 'Matriz / Filial')], max_length=15, null=True),
        ),
    ]
