# Generated by Django 5.2.4 on 2025-10-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_alter_inventariodados_unidade"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="incident",
            name="numero_registro",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
