# Generated by Django 5.2.4 on 2025-10-23 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_incident_id_alter_incident_numero_registro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="numero_registro",
            field=models.PositiveIntegerField(
                unique=True, verbose_name="Número do registro"
            ),
        ),
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Data")),
                ("time", models.TimeField(verbose_name="Hora")),
                (
                    "text",
                    models.CharField(
                        max_length=255, verbose_name="Descrição do evento"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de Calendário",
                "verbose_name_plural": "Eventos de Calendário",
                "ordering": ["date", "time"],
                "indexes": [
                    models.Index(fields=["date"], name="api_calenda_date_acaee6_idx"),
                    models.Index(
                        fields=["user"], name="api_calenda_user_id_1df15a_idx"
                    ),
                ],
            },
        ),
    ]
