# Generated by Django 5.2.4 on 2025-10-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_incident_numero_registro_calendarevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="details",
            field=models.TextField(
                blank=True, null=True, verbose_name="Detalhes do evento"
            ),
        ),
    ]
