# Generated by Django 5.2.4 on 2025-10-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_calendarevent_details"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actionplan",
            name="descricao",
        ),
        migrations.RemoveField(
            model_name="actionplan",
            name="matriz_filial",
        ),
        migrations.RemoveField(
            model_name="actionplan",
            name="processo",
        ),
        migrations.RemoveField(
            model_name="actionplan",
            name="setor_proprietario",
        ),
        migrations.AlterField(
            model_name="actionplan",
            name="prazo",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="actionplan",
            name="responsavel_execucao",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="actionplan",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nao_iniciado", "Não iniciado"),
                    ("andamento", "Em andamento"),
                    ("concluido", "Concluído"),
                ],
                max_length=20,
            ),
        ),
    ]
