# Generated by Django 5.2.4 on 2025-10-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_remove_actionplan_descricao_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actionplan",
            options={
                "ordering": ["ordem_manual", "prazo", "id"],
                "verbose_name": "Plano de Ação",
                "verbose_name_plural": "Planos de Ação",
            },
        ),
        migrations.AddField(
            model_name="actionplan",
            name="ordem_manual",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Define a ordem manual de exibição/prioridade dentro do risco.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="actionplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("nao_iniciado", "Não iniciado"),
                    ("andamento", "Em andamento"),
                    ("concluido", "Concluído"),
                    ("atrasado", "Atrasado"),
                ],
                default="nao_iniciado",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="actionplan",
            index=models.Index(
                fields=["risco", "ordem_manual"], name="api_actionp_risco_i_599276_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actionplan",
            index=models.Index(
                fields=["risco", "prazo"], name="api_actionp_risco_i_b2d1c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actionplan",
            index=models.Index(fields=["status"], name="api_actionp_status_58586c_idx"),
        ),
    ]
