# Generated by Django 5.2.4 on 2025-11-07 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_alter_actionplan_options_actionplan_ordem_manual_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("setor", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "data_login",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Login"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logins",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atividade de Login",
                "verbose_name_plural": "Atividades de Login",
                "ordering": ["-data_login"],
            },
        ),
    ]
