# Generated by Django 5.2.4 on 2025-11-07 02:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_loginactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginactivity",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="loginactivity",
            name="data_login",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data de Login"
            ),
        ),
    ]
