# Generated by Django 5.2.4 on 2025-11-15 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_loginactivity_ip_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modulo", models.CharField(max_length=50)),
                (
                    "operacao",
                    models.CharField(
                        choices=[
                            ("create", "Criação"),
                            ("update", "Atualização"),
                            ("delete", "Exclusão"),
                            ("deactivate", "Desativação"),
                            ("reactivate", "Reativação"),
                            ("export", "Exportação"),
                            ("other", "Outra"),
                        ],
                        max_length=20,
                    ),
                ),
                ("alvo_id", models.PositiveIntegerField(blank=True, null=True)),
                ("detalhe", models.TextField(blank=True, null=True)),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("success", "Sucesso"),
                            ("error", "Erro"),
                            ("invalid", "Tentativa inválida"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Atividade de Usuário",
                "verbose_name_plural": "Logs de Atividades de Usuário",
                "ordering": ["-timestamp"],
            },
        ),
    ]
