# Generated by Django 5.2.4 on 2025-11-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_useractivitylog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivitylog",
            name="operacao",
            field=models.CharField(
                choices=[
                    ("access", "Acesso"),
                    ("create", "Criação"),
                    ("update", "Atualização"),
                    ("delete", "Exclusão"),
                    ("deactivate", "Desativação"),
                    ("reactivate", "Reativação"),
                    ("export", "Exportação"),
                    ("other", "Outra"),
                ],
                max_length=20,
            ),
        ),
    ]
