# Generated by Django 5.2.4 on 2025-11-17 14:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_alter_useractivitylog_operacao"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="useractivitylog",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Log de Atividade de Usuário",
                "verbose_name_plural": "Logs de Atividades de Usuários",
            },
        ),
        migrations.RemoveField(
            model_name="loginactivity",
            name="setor",
        ),
        migrations.RemoveField(
            model_name="useractivitylog",
            name="alvo_id",
        ),
        migrations.AddField(
            model_name="loginactivity",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="loginactivity",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="useractivitylog",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="useractivitylog",
            name="registro_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="useractivitylog",
            name="view_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="loginactivity",
            name="data_login",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="loginactivity",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logins",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="useractivitylog",
            name="modulo",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="useractivitylog",
            name="operacao",
            field=models.CharField(
                choices=[
                    ("ACCESS", "Acesso"),
                    ("CREATE", "Criação"),
                    ("UPDATE", "Atualização"),
                    ("DELETE", "Exclusão"),
                    ("DEACTIVATE", "Desativação"),
                    ("REACTIVATE", "Reativação"),
                    ("EXPORT", "Exportação"),
                    ("OTHER", "Outra"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="useractivitylog",
            name="resultado",
            field=models.CharField(
                choices=[
                    ("SUCCESS", "Sucesso"),
                    ("ERROR", "Erro"),
                    ("INVALID", "Tentativa inválida"),
                ],
                default="SUCCESS",
                max_length=20,
            ),
        ),
    ]
