# Generated by Django 5.2.4 on 2025-11-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_alter_useractivitylog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_data",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="avatar_mime",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
